version: '3.3'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production