# Generated by Django 5.0.2 on 2024-02-27 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoLimite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('limite', models.IntegerField(default=100000)),
                ('agendados', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Agendado', max_length=50)),
                ('report', models.FileField(blank=True, null=True, upload_to='reported/')),
                ('reported', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign_name', models.CharField(default='default_campaign', max_length=200)),
                ('message', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('schedule_date', models.DateField(blank=True, null=True)),
                ('hour_schedule', models.TimeField(auto_now_add=True)),
                ('number', models.IntegerField(default=0)),
                ('number_valid', models.IntegerField(default=0)),
                ('number_invalid', models.IntegerField(default=0)),
                ('id_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_schedule', to='document.document')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scheduled', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_status', to='schedule.schedulestatus')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_numbers', to='schedule.schedule')),
            ],
        ),
    ]
