# Generated by Django 5.0.2 on 2024-02-09 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('report', models.FileField(upload_to='reported/')),
                ('reported', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=200)),
                ('schedule_date', models.DateField(blank=True, null=True)),
                ('hour_schedule', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_scheduled', to='document.document')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scheduled', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_status', to='schedule.schedulestatus')),
            ],
        ),
    ]
