# Generated by Django 5.0.2 on 2024-02-10 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_remove_document_numbers_invalids_and_more'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='hour_schedule',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='id_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_schedule', to='document.document'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_status', to='schedule.schedulestatus'),
        ),
    ]
