# Generated by Django 5.0.2 on 2024-02-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='hour_schedule',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
