# Generated by Django 5.0.2 on 2024-02-09 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_hour_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='id_document',
        ),
    ]
