# Generated by Django 5.0.2 on 2024-02-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_hour_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulestatus',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reported/'),
        ),
    ]
