# Generated by Django 5.0.2 on 2024-02-16 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_schedulestatus_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulestatus',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pernumber', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
