# Generated by Django 5.0.2 on 2024-02-16 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_schedulestatus_status_telefone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Telefone',
        ),
    ]
