# Generated by Django 5.0.2 on 2024-02-16 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_delete_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_numbers', to='schedule.schedule')),
            ],
        ),
    ]
