# Generated by Django 5.0.2 on 2024-02-16 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefone',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telefone',
            name='number_blocked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telefone',
            name='number_invalid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telefone',
            name='number_valid',
            field=models.IntegerField(default=0),
        ),
    ]
