# Generated by Django 5.0.2 on 2024-02-16 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_telefone_number_telefone_number_blocked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefone',
            name='number_blocked',
        ),
    ]
