# Generated by Django 5.0.2 on 2024-02-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_remove_telefone_number_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefone',
            name='number',
        ),
        migrations.RemoveField(
            model_name='telefone',
            name='number_invalid',
        ),
        migrations.RemoveField(
            model_name='telefone',
            name='number_valid',
        ),
        migrations.AddField(
            model_name='schedule',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='number_invalid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedule',
            name='number_valid',
            field=models.IntegerField(default=0),
        ),
    ]
