# Generated by Django 5.0.2 on 2024-02-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_remove_telefone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulestatus',
            name='status',
            field=models.CharField(default='Agendado', max_length=50),
        ),
    ]
