# Generated by Django 5.0.2 on 2024-02-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_schedule_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoLimite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('limite', models.IntegerField(default=100000)),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='limit',
        ),
    ]
