# Generated by Django 5.0.2 on 2024-02-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_agendamentolimite_remove_schedule_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentolimite',
            name='agendados',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
