version: '3.3'

services:
  backend:
    container_name: backend
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/backend
      - ./media/temp_arquivos:/backend/media/temp_arquivos
    env_file:
      - ./dotenv_file/.env    
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_file/.env

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=Y5QHQzRBv4CW
    restart: always
