# Generated by Django 5.0.2 on 2024-02-27 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='temp_arquivos/')),
                ('name', models.CharField(max_length=200)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_scheduled_document', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
