# Generated by Django 5.0.2 on 2024-02-09 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        ('schedule', '0002_alter_schedule_hour_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='numbers_invalids',
        ),
        migrations.AddField(
            model_name='document',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_documents', to='schedule.schedule'),
        ),
    ]
