# Generated by Django 5.0.2 on 2024-02-09 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_remove_document_numbers_invalids_document_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='schedule',
            new_name='id_schedule',
        ),
    ]
