# Generated by Django 5.0.2 on 2024-02-16 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_remove_document_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='number',
        ),
        migrations.RemoveField(
            model_name='document',
            name='number_blockeds',
        ),
        migrations.RemoveField(
            model_name='document',
            name='number_invalid',
        ),
        migrations.RemoveField(
            model_name='document',
            name='number_valid',
        ),
    ]
