# Generated by Django 5.0.2 on 2024-02-09 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_rename_schedule_document_id_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='id_schedule',
            new_name='schedule',
        ),
    ]
