# Generated by Django 5.0.2 on 2024-02-09 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_rename_id_schedule_document_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='schedule',
            new_name='appointment',
        ),
    ]
